import type { CitationStyle } from '@openresearch/citations';

export const CITATION_STYLES: Array<{ id: CitationStyle; labelKey: string }> = [
  { id: 'apa', labelKey: 'citations.styles.apa' },
  { id: 'mla', labelKey: 'citations.styles.mla' },
  { id: 'chicago', labelKey: 'citations.styles.chicago' },
  { id: 'chicago-notes', labelKey: 'citations.styles.chicagoNotes' },
  { id: 'ieee', labelKey: 'citations.styles.ieee' },
  { id: 'harvard', labelKey: 'citations.styles.harvard' },
  { id: 'vancouver', labelKey: 'citations.styles.vancouver' },
  { id: 'nature', labelKey: 'citations.styles.nature' },
  { id: 'science', labelKey: 'citations.styles.science' },
  { id: 'acm', labelKey: 'citations.styles.acm' },
  { id: 'acs', labelKey: 'citations.styles.acs' },
  { id: 'turabian', labelKey: 'citations.styles.turabian' },
  { id: 'ama', labelKey: 'citations.styles.ama' },
  { id: 'nlm', labelKey: 'citations.styles.nlm' },
  { id: 'cse', labelKey: 'citations.styles.cse' },
  { id: 'apsa', labelKey: 'citations.styles.apsa' },
  { id: 'asa', labelKey: 'citations.styles.asa' },
  { id: 'aaa', labelKey: 'citations.styles.aaa' },
  { id: 'mhra', labelKey: 'citations.styles.mhra' },
  { id: 'oxford', labelKey: 'citations.styles.oxford' },
  { id: 'oscola', labelKey: 'citations.styles.oscola' },
  { id: 'bluebook', labelKey: 'citations.styles.bluebook' },
  { id: 'abnt', labelKey: 'citations.styles.abnt' },
  { id: 'iso690', labelKey: 'citations.styles.iso690' },
  { id: 'gbt7714', labelKey: 'citations.styles.gbt7714' },
  { id: 'cell', labelKey: 'citations.styles.cell' },
];
